using System;

namespace Synqra;

/// <summary>
/// The allocation mode of a structured <c>C0DE</c> v8 id — the RFC 9562 variant nibble. RFC 9562 fixes
/// its top bit and leaves the low two bits free, and those two bits are <b>orthogonal dimensions</b>,
/// not a flat four-value enum (model.md §8):
/// <code>
///            pinned    generated
/// committed     8          A
/// staging       9          B
/// </code>
/// <list type="bullet">
/// <item><see cref="Staging"/> selects which <b>semantic registry</b> the family-local code belongs to.
/// The committed and staging registries allocate codes independently, so <c>8C02</c> and <c>9C02</c> need
/// not describe the same thing.</item>
/// <item><see cref="Generated"/> records <b>provenance</b> only. It never changes semantic identity, so
/// <c>8C02 ↔ AC02</c> and <c>9C17 ↔ BC17</c> are the same allocation seen as a pinned type and as a
/// generated instance.</item>
/// </list>
/// Promotion <c>9 → 8</c> is a fresh allocation in the committed registry and may land on a different
/// local code; it is not a bit flip.
/// </summary>
[Flags]
public enum AllocationMode : byte
{
	/// <summary>The fixed RFC 9562 variant bit. Always set on a structured id.</summary>
	Variant = 0x8,

	/// <summary>Registry bit: set ⇒ the staging (working) registry, clear ⇒ the committed (firm) registry.</summary>
	Staging = 0x1,

	/// <summary>Provenance bit: set ⇒ generated by a provider, clear ⇒ pinned by hand in a registry.</summary>
	Generated = 0x2,

	/// <summary><c>8</c> — a hand-pinned allocation in the committed registry. The normative form.</summary>
	CommittedPinned = Variant,

	/// <summary><c>9</c> — a hand-pinned allocation in the staging registry (fixtures, in-flight designs).</summary>
	StagingPinned = Variant | Staging,

	/// <summary><c>A</c> — generated, projecting a committed allocation.</summary>
	CommittedGenerated = Variant | Generated,

	/// <summary><c>B</c> — generated, projecting a staging allocation.</summary>
	StagingGenerated = Variant | Staging | Generated,
}
