// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synqra.Tests;

#nullable disable

namespace Synqra.Tests.Migrations
{
    [DbContext(typeof(TestExtendedSqliteDatabaseContext))]
    partial class TestExtendedSqliteDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Synqra.Command", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("CommandId");

                    b.ToTable("Command");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Command");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Synqra.Tests.MyPocoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MyPocoTask");
                });

            modelBuilder.Entity("Synqra.CreateObjectCommand", b =>
                {
                    b.HasBaseType("Synqra.Command");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetTypeId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CreateObjectCommand");
                });
#pragma warning restore 612, 618
        }
    }
}
