// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Synqra.Tests.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CreateObjectCommandEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Synqra.CreateObjectCommand",
                typeof(CreateObjectCommand),
                baseEntityType,
                discriminatorProperty: "Discriminator",
                discriminatorValue: "CreateObjectCommand",
                propertyCount: 3);

            var collectionId = runtimeEntityType.AddProperty(
                "CollectionId",
                typeof(Guid),
                propertyInfo: typeof(SingleObjectCommand).GetProperty("CollectionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SingleObjectCommand).GetField("_collectionId", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var targetId = runtimeEntityType.AddProperty(
                "TargetId",
                typeof(Guid),
                propertyInfo: typeof(SingleObjectCommand).GetProperty("TargetId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SingleObjectCommand).GetField("_targetId", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var targetTypeId = runtimeEntityType.AddProperty(
                "TargetTypeId",
                typeof(Guid),
                propertyInfo: typeof(SingleObjectCommand).GetProperty("TargetTypeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SingleObjectCommand).GetField("_targetTypeId", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Command");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
