// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Synqra.Tests.CompiledModels
{
    public partial class TestExtendedSqliteDatabaseContextModel
    {
        private TestExtendedSqliteDatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("1a960508-37a3-4972-ae7b-8699e9ad90ec"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var command = CommandEntityType.Create(this);
            var myPocoTask = MyPocoTaskEntityType.Create(this);
            var createObjectCommand = CreateObjectCommandEntityType.Create(this, command);

            CommandEntityType.CreateAnnotations(command);
            MyPocoTaskEntityType.CreateAnnotations(myPocoTask);
            CreateObjectCommandEntityType.CreateAnnotations(createObjectCommand);

            AddAnnotation("ProductVersion", "10.0.3");
        }
    }
}
