// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Synqra.Tests;
using Synqra.Tests.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TestExtendedSqliteDatabaseContext), typeof(TestExtendedSqliteDatabaseContextModel))]
