<Project>
	<PropertyGroup>
		<SynqraBuildBox>$(Temp)\Synqra\Build\$([System.Guid]::NewGuid())</SynqraBuildBox>
	</PropertyGroup>
	<ItemGroup>
		<CompilerVisibleProperty Include="SynqraBuildBox" />
	</ItemGroup>

	<Target Name="_SbxSG_BeforeCoreCompile" BeforeTargets="CoreCompile">
		<Message Text="Running Synqra.BinarySerializer.SourceGenerator _SbxSG_BeforeCoreCompile $(SynqraBuildBox)" Importance="high" />
	</Target>

	<Target Name="_SbxSG_AfterCoreCompile" AfterTargets="CoreCompile">
		<Message Text="Running Synqra.BinarySerializer.SourceGenerator _SbxSG_AfterCoreCompile $(SynqraBuildBox)" Importance="high" />
		<ItemGroup>
			<_tmp Include="$(SynqraBuildBox)\*.*" />
		</ItemGroup>
		<Message Text="SynqraBuildBox=$(SynqraBuildBox) _tmp=@(_tmp) ProjectDir=$(ProjectDir)" Importance="high" />
		<Copy SourceFiles="@(_tmp)" DestinationFolder="$(ProjectDir)" Retries="5" OverwriteReadOnlyFiles="true" />
		<Message Text="Copied: @(_tmp)" Importance="high" />
	</Target>
</Project>
