// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synqra.Projection.Sqlite;

#nullable disable

namespace Synqra.Projection.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20260226181045_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");
#pragma warning restore 612, 618
        }
    }
}
