// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synqra.Projection.Sqlite;

#nullable disable

namespace Synqra.Projection.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDatabaseContext))]
    partial class SqliteDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Synqra.Command", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("CommandId");

                    b.ToTable("Command");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Command");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Synqra.CreateObjectCommand", b =>
                {
                    b.HasBaseType("Synqra.Command");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetTypeId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CreateObjectCommand");
                });
#pragma warning restore 612, 618
        }
    }
}
