<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>$(CommonVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <InternalsVisibleTo Include="Synqra.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Synqra\Synqra.csproj" />
    <ProjectReference Include="..\Synqra.AppendStorage.Abstractions\Synqra.AppendStorage.Abstractions.csproj" />
    <ProjectReference Include="..\Synqra.Model\Synqra.Model.csproj" />
  </ItemGroup>

</Project>
